# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  test:
    jobs:
      - build

jobs:
  build:
    docker:
      # - image: circleci/python:3.6.2-stretch-browsers
      # - image: github/super-linter
      - image: ubuntu:focal
    steps:
        - run:
          command: |
            apt install --no-upgrade --no-install-recommends \
              openssh-server \
              git
      # - run:
      #     name: "Install git and SSH client"
      #     command: |
      #       apk add \
      #           --update-cache \
      #           --no-progress \
      #           openssh-client=7.6 \
      #           dash && \
      #       rm -rf /var/cache/apk/*
      #       # now link bash to sh instead of busybox
      #       ln -fs /usr/bin/dash /bin/sh

      - checkout
      - run:
          name: hmm
          command: |
            touch $HOME/test.py
            readlink -f $(which sh)
            # sleep 7m
