# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

workflows:
  test:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Prep alpine image for circle
          command: |
            apk add \
                --update-cache \
                --no-progress \
                openssh-client \
                tar \
                git \
                gzip \
                ca-certificates \
                dash && \
            rm -rf /var/cache/apk/*
            # now link bash to sh instead of busybox
            # ln -fs /bin/dash /bin/sh
      - checkout
      - run:
          name: hmm
          command: |
            readlink -f $(which sh)
