# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1 # Use the Heroku orb in your config

workflows:
  test:
    jobs:
      - build

jobs:
  build:
    docker:
      # - image: circleci/python:3.6.2-stretch-browsers
      - image: github/super-linter
    steps:
      - checkout
      - run
          name: hmmm
          command: |
            touch $HOME/test.py
            sleep 7m